---
# tasks file for serverspec - EL

- name: Installing epel-release on EL systems
  package:
    name: epel-release
    state: present
    update_cache: yes

- name: "Installing {{ ruby_app_el_package }} on EL based systems as required for {{ serverspec_app }}"
  package:
    name: "{{ ruby_app_el_package }}"
    state: "{{ ruby_desired_state }}"
    update_cache: yes

- name: "Installing {{ serverspec_app }} on EL based systems"
  gem:
    name: "{{ serverspec_app }}"
    state: "{{ serverspec_desired_state }}"
    user_install: "{{ serverspec_user_install }}"
    include_dependencies: "{{ serverspec_include_dependencies }}"
