---
# tasks file for serverspec - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Installing {{ ruby_app_debian_package }} as required for {{ serverspec_app }}
  package:
    name: "{{ ruby_app_debian_package }}"
    state: "{{ ruby_desired_state }}"
    force_apt_get: yes
    update_cache: yes

- name: Debian/Ubuntu Family | Installing {{ serverspec_app }}
  gem:
    name: "{{ serverspec_app }}"
    state: "{{ serverspec_desired_state }}"
    user_install: "{{ serverspec_user_install }}"
    include_dependencies: "{{ serverspec_include_dependencies }}"
