---
# tasks file for serverspec - EL Family

- name: EL Family | Installing epel-release
  package:
    name: epel-release
    state: present
    update_cache: yes

- name: EL Family | Installing {{ ruby_app_el_package }} as required for {{ serverspec_app }}
  package:
    name: "{{ ruby_app_el_package }}"
    state: "{{ ruby_desired_state }}"
    update_cache: yes

- name: EL Family | Installing {{ serverspec_app }}
  gem:
    name: "{{ serverspec_app }}"
    state: "{{ serverspec_desired_state }}"
    user_install: "{{ serverspec_user_install }}"
    include_dependencies: "{{ serverspec_include_dependencies }}"
