---
# tasks file for serverspec - Debian

- name: "Installing {{ ruby_app_debian_package }} on Debian based systems as required for {{ serverspec_app }}"
  package:
    name: "{{ ruby_app_debian_package }}"
    state: "{{ ruby_desired_state }}"
    force_apt_get: yes
    update_cache: yes

- name: "Installing {{ serverspec_app }} on Debian based systems"
  gem:
    name: "{{ serverspec_app }}"
    state: "{{ serverspec_desired_state }}"
    user_install: "{{ serverspec_user_install }}"
    include_dependencies: "{{ serverspec_include_dependencies }}"
